package corestrtests

// Auto-generated by Batch 2.2 split from S21_001_S21_CloneSlice_Empty_Reflect_test.go.
// See spec/01-app/29-corestrtests-phase2-merge-plan.md.

import (
	"testing"

	"github.com/alimtvnetwork/core/coredata/corestr"
	"github.com/alimtvnetwork/core/coretests/args"
)

func Test_CloneSlice_with_items_FromS21(t *testing.T) {
	safeTest(t, "Test_CloneSlice_with_items_FromS21", func() {
		// Arrange
		items := []string{"a", "b", "c"}

		// Act
		clone := corestr.CloneSlice(items)

		// Assert
		actual := args.Map{"result": len(clone) != 3}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "CloneSlice returns 3 items", actual)
		actual = args.Map{"result": clone[0] != "a" || clone[1] != "b" || clone[2] != "c"}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "CloneSlice returns correct values -- a,b,c", actual)
		// Verify independence
		items[0] = "modified"
		actual = args.Map{"result": clone[0] == "modified"}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "CloneSlice returns independent copy -- mutation should not propagate", actual)
	})
}

func Test_CloneSlice_empty_FromS21(t *testing.T) {
	safeTest(t, "Test_CloneSlice_empty_FromS21", func() {
		// Arrange
		items := []string{}

		// Act
		clone := corestr.CloneSlice(items)

		// Assert
		actual := args.Map{"result": clone == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "CloneSlice returns non-nil -- empty input", actual)
		actual = args.Map{"result": len(clone) != 0}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "CloneSlice returns empty slice", actual)
	})
}

func Test_CloneSlice_nil_FromS21(t *testing.T) {
	safeTest(t, "Test_CloneSlice_nil_FromS21", func() {
		// Arrange
		var items []string

		// Act
		clone := corestr.CloneSlice(items)

		// Assert
		actual := args.Map{"result": clone == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "CloneSlice returns non-nil -- nil input", actual)
		actual = args.Map{"result": len(clone) != 0}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "CloneSlice returns empty slice -- nil input", actual)
	})
}

func Test_CloneSlice_CloneSliceIf_clone_true_FromS21(t *testing.T) {
	safeTest(t, "Test_CloneSlice_CloneSliceIf_clone_true_FromS21", func() {
		// Arrange
		items := []string{"x", "y"}

		// Act
		clone := corestr.CloneSliceIf(true, items...)

		// Assert
		actual := args.Map{"result": len(clone) != 2}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "CloneSliceIf returns 2 items -- clone true", actual)
		items[0] = "modified"
		actual = args.Map{"result": clone[0] == "modified"}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "CloneSliceIf returns independent copy -- clone true", actual)
	})
}

func Test_CloneSlice_CloneSliceIf_clone_false_FromS21(t *testing.T) {
	safeTest(t, "Test_CloneSlice_CloneSliceIf_clone_false_FromS21", func() {
		// Arrange
		items := []string{"x", "y"}

		// Act
		result := corestr.CloneSliceIf(false, items...)

		// Assert
		actual := args.Map{"result": len(result) != 2}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "CloneSliceIf returns 2 items -- clone false", actual)
		// When clone=false, should return same slice (shared backing array)
		items[0] = "modified"
		actual = args.Map{"result": result[0] != "modified"}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "CloneSliceIf returns same reference -- clone false", actual)
	})
}

func Test_CloneSlice_CloneSliceIf_empty_FromS21(t *testing.T) {
	safeTest(t, "Test_CloneSlice_CloneSliceIf_empty_FromS21", func() {
		// Arrange & Act
		result := corestr.CloneSliceIf(true)

		// Assert
		actual := args.Map{"result": result == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "CloneSliceIf returns non-nil -- empty variadic", actual)
		actual = args.Map{"result": len(result) != 0}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "CloneSliceIf returns empty slice", actual)
	})
}

