// MIT License
// 
// Copyright (c) 2020–2026
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package corestrtests

// Auto-generated by Batch 2.2 split from S21_001_S21_CloneSlice_Empty_Reflect_test.go.
// See spec/01-app/29-corestrtests-phase2-merge-plan.md.

import (
	"testing"

	"github.com/alimtvnetwork/core-v8/coredata/corestr"
	"github.com/alimtvnetwork/core-v8/coretests/args"
)

func Test_CloneSlice_with_items_FromS21(t *testing.T) {
	safeTest(t, "Test_CloneSlice_with_items_FromS21", func() {
		// Arrange
		items := []string{"a", "b", "c"}

		// Act
		clone := corestr.CloneSlice(items)

		// Assert
		actual := args.Map{"result": len(clone) != 3}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "CloneSlice returns 3 items", actual)
		actual = args.Map{"result": clone[0] != "a" || clone[1] != "b" || clone[2] != "c"}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "CloneSlice returns correct values -- a,b,c", actual)
		// Verify independence
		items[0] = "modified"
		actual = args.Map{"result": clone[0] == "modified"}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "CloneSlice returns independent copy -- mutation should not propagate", actual)
	})
}

func Test_CloneSlice_empty_FromS21(t *testing.T) {
	safeTest(t, "Test_CloneSlice_empty_FromS21", func() {
		// Arrange
		items := []string{}

		// Act
		clone := corestr.CloneSlice(items)

		// Assert
		actual := args.Map{"result": clone == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "CloneSlice returns non-nil -- empty input", actual)
		actual = args.Map{"result": len(clone) != 0}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "CloneSlice returns empty slice", actual)
	})
}

func Test_CloneSlice_nil_FromS21(t *testing.T) {
	safeTest(t, "Test_CloneSlice_nil_FromS21", func() {
		// Arrange
		var items []string

		// Act
		clone := corestr.CloneSlice(items)

		// Assert
		actual := args.Map{"result": clone == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "CloneSlice returns non-nil -- nil input", actual)
		actual = args.Map{"result": len(clone) != 0}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "CloneSlice returns empty slice -- nil input", actual)
	})
}

func Test_CloneSlice_CloneSliceIf_clone_true_FromS21(t *testing.T) {
	safeTest(t, "Test_CloneSlice_CloneSliceIf_clone_true_FromS21", func() {
		// Arrange
		items := []string{"x", "y"}

		// Act
		clone := corestr.CloneSliceIf(true, items...)

		// Assert
		actual := args.Map{"result": len(clone) != 2}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "CloneSliceIf returns 2 items -- clone true", actual)
		items[0] = "modified"
		actual = args.Map{"result": clone[0] == "modified"}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "CloneSliceIf returns independent copy -- clone true", actual)
	})
}

func Test_CloneSlice_CloneSliceIf_clone_false_FromS21(t *testing.T) {
	safeTest(t, "Test_CloneSlice_CloneSliceIf_clone_false_FromS21", func() {
		// Arrange
		items := []string{"x", "y"}

		// Act
		result := corestr.CloneSliceIf(false, items...)

		// Assert
		actual := args.Map{"result": len(result) != 2}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "CloneSliceIf returns 2 items -- clone false", actual)
		// When clone=false, should return same slice (shared backing array)
		items[0] = "modified"
		actual = args.Map{"result": result[0] != "modified"}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "CloneSliceIf returns same reference -- clone false", actual)
	})
}

func Test_CloneSlice_CloneSliceIf_empty_FromS21(t *testing.T) {
	safeTest(t, "Test_CloneSlice_CloneSliceIf_empty_FromS21", func() {
		// Arrange & Act
		result := corestr.CloneSliceIf(true)

		// Assert
		actual := args.Map{"result": result == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "CloneSliceIf returns non-nil -- empty variadic", actual)
		actual = args.Map{"result": len(result) != 0}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "CloneSliceIf returns empty slice", actual)
	})
}


func Test_CloneSlice_Empty_FromSeg1(t *testing.T) {
	safeTest(t, "Test_CloneSlice_Empty_FromSeg1", func() {
		// Arrange
		result := corestr.CloneSlice([]string{})

		// Act
		actual := args.Map{"len": len(result)}

		// Assert
		expected := args.Map{"len": 0}
		expected.ShouldBeEqual(t, 0, "CloneSlice returns empty -- empty input", actual)
	})
}

func Test_CloneSlice_WithItems_FromSeg1(t *testing.T) {
	safeTest(t, "Test_CloneSlice_WithItems_FromSeg1", func() {
		// Arrange
		src := []string{"a", "b", "c"}
		result := corestr.CloneSlice(src)

		// Act
		actual := args.Map{
			"len": len(result),
			"eq": result[0] == "a" && result[2] == "c",
		}

		// Assert
		expected := args.Map{
			"len": 3,
			"eq": true,
		}
		expected.ShouldBeEqual(t, 0, "CloneSlice returns copy -- with items", actual)
	})
}

func Test_CloneSlice_Nil_FromSeg1(t *testing.T) {
	safeTest(t, "Test_CloneSlice_Nil_FromSeg1", func() {
		// Arrange
		result := corestr.CloneSlice(nil)

		// Act
		actual := args.Map{"len": len(result)}

		// Assert
		expected := args.Map{"len": 0}
		expected.ShouldBeEqual(t, 0, "CloneSlice returns empty -- nil input", actual)
	})
}

func Test_CloneSliceIf_Clone_FromSeg1(t *testing.T) {
	safeTest(t, "Test_CloneSliceIf_Clone_FromSeg1", func() {
		// Arrange
		result := corestr.CloneSliceIf(true, "a", "b")

		// Act
		actual := args.Map{
			"len": len(result),
			"first": result[0],
		}

		// Assert
		expected := args.Map{
			"len": 2,
			"first": "a",
		}
		expected.ShouldBeEqual(t, 0, "CloneSliceIf returns clone -- isClone true", actual)
	})
}

func Test_CloneSliceIf_NoClone_FromSeg1(t *testing.T) {
	safeTest(t, "Test_CloneSliceIf_NoClone_FromSeg1", func() {
		// Arrange
		result := corestr.CloneSliceIf(false, "a", "b")

		// Act
		actual := args.Map{"len": len(result)}

		// Assert
		expected := args.Map{"len": 2}
		expected.ShouldBeEqual(t, 0, "CloneSliceIf returns same -- isClone false", actual)
	})
}

func Test_CloneSliceIf_Empty_FromSeg1(t *testing.T) {
	safeTest(t, "Test_CloneSliceIf_Empty_FromSeg1", func() {
		// Arrange
		result := corestr.CloneSliceIf(true)

		// Act
		actual := args.Map{"len": len(result)}

		// Assert
		expected := args.Map{"len": 0}
		expected.ShouldBeEqual(t, 0, "CloneSliceIf returns empty -- no items", actual)
	})
}

