// MIT License
// 
// Copyright (c) 2020–2026
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package corestrtests

// Auto-generated by Batch 2.2 split from S21_001_S21_CloneSlice_Empty_Reflect_test.go.
// See spec/01-app/29-corestrtests-phase2-merge-plan.md.

import (
	"testing"

	"github.com/alimtvnetwork/core/coredata/corestr"
	"github.com/alimtvnetwork/core/coretests/args"
)

func Test_Empty_Collection_FromS21(t *testing.T) {
	safeTest(t, "Test_Empty_Collection_FromS21", func() {
		// Act
		c := corestr.Empty.Collection()

		// Assert
		actual := args.Map{"result": c == nil || !c.IsEmpty()}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Empty.Collection returns empty collection", actual)
	})
}

func Test_Empty_LinkedList_FromS21(t *testing.T) {
	safeTest(t, "Test_Empty_LinkedList_FromS21", func() {
		// Act
		ll := corestr.Empty.LinkedList()

		// Assert
		actual := args.Map{"result": ll == nil || ll.Length() != 0}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Empty.LinkedList returns empty linked list", actual)
	})
}

func Test_Empty_SimpleSlice_FromS21(t *testing.T) {
	safeTest(t, "Test_Empty_SimpleSlice_FromS21", func() {
		// Act
		ss := corestr.Empty.SimpleSlice()

		// Assert
		actual := args.Map{"result": ss == nil || !ss.IsEmpty()}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Empty.SimpleSlice returns empty simple slice", actual)
	})
}

func Test_Empty_KeyAnyValuePair_FromS21(t *testing.T) {
	safeTest(t, "Test_Empty_KeyAnyValuePair_FromS21", func() {
		// Act
		kv := corestr.Empty.KeyAnyValuePair()

		// Assert
		actual := args.Map{"result": kv == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Empty.KeyAnyValuePair returns non-nil", actual)
	})
}

func Test_Empty_KeyValuePair_FromS21(t *testing.T) {
	safeTest(t, "Test_Empty_KeyValuePair_FromS21", func() {
		// Act
		kv := corestr.Empty.KeyValuePair()

		// Assert
		actual := args.Map{"result": kv == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Empty.KeyValuePair returns non-nil", actual)
	})
}

func Test_Empty_KeyValueCollection_FromS21(t *testing.T) {
	safeTest(t, "Test_Empty_KeyValueCollection_FromS21", func() {
		// Act
		kvc := corestr.Empty.KeyValueCollection()

		// Assert
		actual := args.Map{"result": kvc == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Empty.KeyValueCollection returns non-nil", actual)
	})
}

func Test_Empty_LinkedCollections_FromS21(t *testing.T) {
	safeTest(t, "Test_Empty_LinkedCollections_FromS21", func() {
		// Act
		lc := corestr.Empty.LinkedCollections()

		// Assert
		actual := args.Map{"result": lc == nil || lc.Length() != 0}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Empty.LinkedCollections returns empty", actual)
	})
}

func Test_Empty_LeftRight_FromS21(t *testing.T) {
	safeTest(t, "Test_Empty_LeftRight_FromS21", func() {
		// Act
		lr := corestr.Empty.LeftRight()

		// Assert
		actual := args.Map{"result": lr == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Empty.LeftRight returns non-nil", actual)
	})
}

func Test_Empty_SimpleStringOnce_FromS21(t *testing.T) {
	safeTest(t, "Test_Empty_SimpleStringOnce_FromS21", func() {
		// Act
		sso := corestr.Empty.SimpleStringOnce()

		// Assert
		actual := args.Map{"result": sso.IsInitialized()}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Empty.SimpleStringOnce returns uninitialized", actual)
	})
}

func Test_Empty_SimpleStringOncePtr_FromS21(t *testing.T) {
	safeTest(t, "Test_Empty_SimpleStringOncePtr_FromS21", func() {
		// Act
		sso := corestr.Empty.SimpleStringOncePtr()

		// Assert
		actual := args.Map{"result": sso == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Empty.SimpleStringOncePtr returns non-nil", actual)
	})
}

func Test_Empty_Hashset_FromS21(t *testing.T) {
	safeTest(t, "Test_Empty_Hashset_FromS21", func() {
		// Act
		hs := corestr.Empty.Hashset()

		// Assert
		actual := args.Map{"result": hs == nil || hs.Length() != 0}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Empty.Hashset returns empty hashset", actual)
	})
}

func Test_Empty_HashsetsCollection_FromS21(t *testing.T) {
	safeTest(t, "Test_Empty_HashsetsCollection_FromS21", func() {
		// Act
		hsc := corestr.Empty.HashsetsCollection()

		// Assert
		actual := args.Map{"result": hsc == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Empty.HashsetsCollection returns non-nil", actual)
	})
}

func Test_Empty_Hashmap_FromS21(t *testing.T) {
	safeTest(t, "Test_Empty_Hashmap_FromS21", func() {
		// Act
		hm := corestr.Empty.Hashmap()

		// Assert
		actual := args.Map{"result": hm == nil || hm.Length() != 0}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Empty.Hashmap returns empty hashmap", actual)
	})
}

func Test_Empty_CharCollectionMap_FromS21(t *testing.T) {
	safeTest(t, "Test_Empty_CharCollectionMap_FromS21", func() {
		// Act
		ccm := corestr.Empty.CharCollectionMap()

		// Assert
		actual := args.Map{"result": ccm == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Empty.CharCollectionMap returns non-nil", actual)
	})
}

func Test_Empty_KeyValuesCollection_FromS21(t *testing.T) {
	safeTest(t, "Test_Empty_KeyValuesCollection_FromS21", func() {
		// Act
		kvc := corestr.Empty.KeyValuesCollection()

		// Assert
		actual := args.Map{"result": kvc == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Empty.KeyValuesCollection returns non-nil", actual)
	})
}

func Test_Empty_CollectionsOfCollection_FromS21(t *testing.T) {
	safeTest(t, "Test_Empty_CollectionsOfCollection_FromS21", func() {
		// Act
		coc := corestr.Empty.CollectionsOfCollection()

		// Assert
		actual := args.Map{"result": coc == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Empty.CollectionsOfCollection returns non-nil", actual)
	})
}

func Test_Empty_CharHashsetMap_FromS21(t *testing.T) {
	safeTest(t, "Test_Empty_CharHashsetMap_FromS21", func() {
		// Act
		chm := corestr.Empty.CharHashsetMap()

		// Assert
		actual := args.Map{"result": chm == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Empty.CharHashsetMap returns non-nil", actual)
	})
}

