package corestrtests

// Auto-generated by Batch 2.2 split from S20_001_S20_NonChainedNodes_HashmapDiff_test.go.
// See spec/01-app/29-corestrtests-phase2-merge-plan.md.

import (
	"testing"

	"github.com/alimtvnetwork/core/coredata/corestr"
	"github.com/alimtvnetwork/core/coretests/args"
)

func Test_HashmapDiff_Length_nil_FromS20(t *testing.T) {
	safeTest(t, "Test_HashmapDiff_Length_nil_FromS20", func() {
		// Arrange
		var hd *corestr.HashmapDiff

		// Act
		result := hd.Length()

		// Assert
		actual := args.Map{"result": result != 0}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Length returns 0 -- nil receiver", actual)
	})
}

func Test_HashmapDiff_Length_with_items_FromS20(t *testing.T) {
	safeTest(t, "Test_HashmapDiff_Length_with_items_FromS20", func() {
		// Arrange
		hd := corestr.HashmapDiff(map[string]string{"a": "1", "b": "2"})

		// Act
		result := hd.Length()

		// Assert
		actual := args.Map{"result": result != 2}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Length returns 2 -- two items", actual)
	})
}

func Test_HashmapDiff_IsEmpty_true_FromS20(t *testing.T) {
	safeTest(t, "Test_HashmapDiff_IsEmpty_true_FromS20", func() {
		// Arrange
		hd := corestr.HashmapDiff(map[string]string{})

		// Act & Assert
		actual := args.Map{"result": hd.IsEmpty()}
		expected := args.Map{"result": true}
		expected.ShouldBeEqual(t, 0, "IsEmpty returns true -- empty map", actual)
	})
}

func Test_HashmapDiff_IsEmpty_false_FromS20(t *testing.T) {
	safeTest(t, "Test_HashmapDiff_IsEmpty_false_FromS20", func() {
		// Arrange
		hd := corestr.HashmapDiff(map[string]string{"a": "1"})

		// Act & Assert
		actual := args.Map{"result": hd.IsEmpty()}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "IsEmpty returns false -- has item", actual)
	})
}

func Test_HashmapDiff_HasAnyItem_FromS20(t *testing.T) {
	safeTest(t, "Test_HashmapDiff_HasAnyItem_FromS20", func() {
		// Arrange
		hd := corestr.HashmapDiff(map[string]string{"a": "1"})

		// Act & Assert
		actual := args.Map{"result": hd.HasAnyItem()}
		expected := args.Map{"result": true}
		expected.ShouldBeEqual(t, 0, "HasAnyItem returns true -- has item", actual)
	})
}

func Test_HashmapDiff_LastIndex_FromS20(t *testing.T) {
	safeTest(t, "Test_HashmapDiff_LastIndex_FromS20", func() {
		// Arrange
		hd := corestr.HashmapDiff(map[string]string{"a": "1", "b": "2", "c": "3"})

		// Act
		result := hd.LastIndex()

		// Assert
		actual := args.Map{"result": result != 2}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "LastIndex returns 2 -- 3 items", actual)
	})
}

func Test_HashmapDiff_AllKeysSorted_FromS20(t *testing.T) {
	safeTest(t, "Test_HashmapDiff_AllKeysSorted_FromS20", func() {
		// Arrange
		hd := corestr.HashmapDiff(map[string]string{"c": "3", "a": "1", "b": "2"})

		// Act
		keys := hd.AllKeysSorted()

		// Assert
		actual := args.Map{"result": len(keys) != 3}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "AllKeysSorted returns 3 keys", actual)
		actual = args.Map{"result": keys[0] != "a" || keys[1] != "b" || keys[2] != "c"}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "AllKeysSorted returns sorted keys -- a,b,c", actual)
	})
}

func Test_HashmapDiff_MapAnyItems_FromS20(t *testing.T) {
	safeTest(t, "Test_HashmapDiff_MapAnyItems_FromS20", func() {
		// Arrange
		hd := corestr.HashmapDiff(map[string]string{"x": "10"})

		// Act
		result := hd.MapAnyItems()

		// Assert
		actual := args.Map{"result": len(result) != 1}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "MapAnyItems returns 1 item", actual)
		actual = args.Map{"result": result["x"] != "10"}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "MapAnyItems has x=10", actual)
	})
}

func Test_HashmapDiff_MapAnyItems_nil_FromS20(t *testing.T) {
	safeTest(t, "Test_HashmapDiff_MapAnyItems_nil_FromS20", func() {
		// Arrange
		var hd *corestr.HashmapDiff

		// Act
		result := hd.MapAnyItems()

		// Assert
		actual := args.Map{"result": result == nil || len(result) != 0}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "MapAnyItems returns empty map -- nil receiver", actual)
	})
}

func Test_HashmapDiff_Raw_nil_FromS20(t *testing.T) {
	safeTest(t, "Test_HashmapDiff_Raw_nil_FromS20", func() {
		// Arrange
		var hd *corestr.HashmapDiff

		// Act
		result := hd.Raw()

		// Assert
		actual := args.Map{"result": result == nil || len(result) != 0}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Raw returns empty map -- nil receiver", actual)
	})
}

func Test_HashmapDiff_Raw_with_items_FromS20(t *testing.T) {
	safeTest(t, "Test_HashmapDiff_Raw_with_items_FromS20", func() {
		// Arrange
		hd := corestr.HashmapDiff(map[string]string{"a": "1"})

		// Act
		result := hd.Raw()

		// Assert
		actual := args.Map{"result": len(result) != 1 || result["a"] != "1"}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Raw returns underlying map -- has items", actual)
	})
}

func Test_HashmapDiff_IsRawEqual_true_FromS20(t *testing.T) {
	safeTest(t, "Test_HashmapDiff_IsRawEqual_true_FromS20", func() {
		// Arrange
		hd := corestr.HashmapDiff(map[string]string{"a": "1"})

		// Act
		result := hd.IsRawEqual(map[string]string{"a": "1"})

		// Assert
		actual := args.Map{"result": result}
		expected := args.Map{"result": true}
		expected.ShouldBeEqual(t, 0, "IsRawEqual returns true -- same maps", actual)
	})
}

func Test_HashmapDiff_IsRawEqual_false_FromS20(t *testing.T) {
	safeTest(t, "Test_HashmapDiff_IsRawEqual_false_FromS20", func() {
		// Arrange
		hd := corestr.HashmapDiff(map[string]string{"a": "1"})

		// Act
		result := hd.IsRawEqual(map[string]string{"a": "2"})

		// Assert
		actual := args.Map{"result": result}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "IsRawEqual returns false -- different values", actual)
	})
}

func Test_HashmapDiff_HasAnyChanges_FromS20(t *testing.T) {
	safeTest(t, "Test_HashmapDiff_HasAnyChanges_FromS20", func() {
		// Arrange
		hd := corestr.HashmapDiff(map[string]string{"a": "1"})

		// Act
		result := hd.HasAnyChanges(map[string]string{"a": "2"})

		// Assert
		actual := args.Map{"result": result}
		expected := args.Map{"result": true}
		expected.ShouldBeEqual(t, 0, "HasAnyChanges returns true -- different values", actual)
	})
}

func Test_HashmapDiff_HasAnyChanges_no_changes_FromS20(t *testing.T) {
	safeTest(t, "Test_HashmapDiff_HasAnyChanges_no_changes_FromS20", func() {
		// Arrange
		hd := corestr.HashmapDiff(map[string]string{"a": "1"})

		// Act
		result := hd.HasAnyChanges(map[string]string{"a": "1"})

		// Assert
		actual := args.Map{"result": result}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "HasAnyChanges returns false -- same values", actual)
	})
}

func Test_HashmapDiff_DiffRaw_FromS20(t *testing.T) {
	safeTest(t, "Test_HashmapDiff_DiffRaw_FromS20", func() {
		// Arrange
		hd := corestr.HashmapDiff(map[string]string{"a": "1", "b": "2"})

		// Act
		diff := hd.DiffRaw(map[string]string{"a": "1", "b": "3"})

		// Assert
		actual := args.Map{"result": diff == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "DiffRaw returns non-nil -- has diff", actual)
		actual = args.Map{"result": diff["b"] != "2"}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "DiffRaw contains b=2 -- left value for changed key", actual)
	})
}

func Test_HashmapDiff_HashmapDiffUsingRaw_no_diff_FromS20(t *testing.T) {
	safeTest(t, "Test_HashmapDiff_HashmapDiffUsingRaw_no_diff_FromS20", func() {
		// Arrange
		hd := corestr.HashmapDiff(map[string]string{"a": "1"})

		// Act
		result := hd.HashmapDiffUsingRaw(map[string]string{"a": "1"})

		// Assert
		actual := args.Map{"result": len(result) != 0}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "HashmapDiffUsingRaw returns empty -- no diff", actual)
	})
}

func Test_HashmapDiff_DiffJsonMessage_FromS20(t *testing.T) {
	safeTest(t, "Test_HashmapDiff_DiffJsonMessage_FromS20", func() {
		// Arrange
		hd := corestr.HashmapDiff(map[string]string{"a": "1"})

		// Act
		msg := hd.DiffJsonMessage(map[string]string{"a": "2"})

		// Assert
		actual := args.Map{"result": msg == ""}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "DiffJsonMessage returns non-empty -- has diff", actual)
	})
}

func Test_HashmapDiff_ToStringsSliceOfDiffMap_FromS20(t *testing.T) {
	safeTest(t, "Test_HashmapDiff_ToStringsSliceOfDiffMap_FromS20", func() {
		// Arrange
		hd := corestr.HashmapDiff(map[string]string{"a": "1"})
		diffMap := map[string]string{"a": "2"}

		// Act
		result := hd.ToStringsSliceOfDiffMap(diffMap)

		// Assert
		actual := args.Map{"result": len(result) == 0}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "ToStringsSliceOfDiffMap returns non-empty -- has items", actual)
	})
}

func Test_HashmapDiff_ShouldDiffMessage_FromS20(t *testing.T) {
	safeTest(t, "Test_HashmapDiff_ShouldDiffMessage_FromS20", func() {
		// Arrange
		hd := corestr.HashmapDiff(map[string]string{"a": "1"})

		// Act
		msg := hd.ShouldDiffMessage("test", map[string]string{"a": "2"})

		// Assert
		actual := args.Map{"result": msg == ""}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "ShouldDiffMessage returns non-empty -- has diff", actual)
	})
}

func Test_HashmapDiff_LogShouldDiffMessage_FromS20(t *testing.T) {
	safeTest(t, "Test_HashmapDiff_LogShouldDiffMessage_FromS20", func() {
		// Arrange
		hd := corestr.HashmapDiff(map[string]string{"a": "1"})

		// Act
		msg := hd.LogShouldDiffMessage("test", map[string]string{"a": "2"})

		// Assert
		actual := args.Map{"result": msg == ""}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "LogShouldDiffMessage returns non-empty -- has diff", actual)
	})
}

func Test_HashmapDiff_RawMapStringAnyDiff_FromS20(t *testing.T) {
	safeTest(t, "Test_HashmapDiff_RawMapStringAnyDiff_FromS20", func() {
		// Arrange
		hd := corestr.HashmapDiff(map[string]string{"k": "v"})

		// Act
		result := hd.RawMapStringAnyDiff()

		// Assert
		actual := args.Map{"result": result == nil || len(result) != 1}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "RawMapStringAnyDiff returns map with 1 item", actual)
	})
}

func Test_HashmapDiff_Serialize_FromS20(t *testing.T) {
	safeTest(t, "Test_HashmapDiff_Serialize_FromS20", func() {
		// Arrange
		hd := corestr.HashmapDiff(map[string]string{"a": "1"})

		// Act
		data, err := hd.Serialize()

		// Assert
		actual := args.Map{"result": err != nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Serialize returns no error", actual)
		actual = args.Map{"result": len(data) == 0}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Serialize returns non-empty bytes", actual)
	})
}

func Test_HashmapDiff_Deserialize_FromS20(t *testing.T) {
	safeTest(t, "Test_HashmapDiff_Deserialize_FromS20", func() {
		// Arrange
		hd := corestr.HashmapDiff(map[string]string{"a": "1"})

		// Act
		var target map[string]string
		err := hd.Deserialize(&target)

		// Assert
		actual := args.Map{"result": err != nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Deserialize returns no error", actual)
		actual = args.Map{"result": target["a"] != "1"}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Deserialize target has a=1", actual)
	})
}
