// MIT License
// 
// Copyright (c) 2020–2026
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package corestrtests

// Auto-generated by Batch 2.2 split from S22_001_S22_FromSplit_Creators_test.go.
// See spec/01-app/29-corestrtests-phase2-merge-plan.md.

import (
	"testing"

	"github.com/alimtvnetwork/core/coredata/corestr"
	"github.com/alimtvnetwork/core/coretests/args"
)

func Test_LeftRightFromSplit_basic_FromS22(t *testing.T) {
	safeTest(t, "Test_LeftRightFromSplit_basic_FromS22", func() {
		// Arrange & Act
		lr := corestr.LeftRightFromSplit("key=value", "=")

		// Assert
		actual := args.Map{"result": lr.Left != "key"}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "LeftRightFromSplit Left returns key", actual)
		actual = args.Map{"result": lr.Right != "value"}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "LeftRightFromSplit Right returns value", actual)
	})
}

func Test_LeftRightFromSplit_no_sep_FromS22(t *testing.T) {
	safeTest(t, "Test_LeftRightFromSplit_no_sep_FromS22", func() {
		// Arrange & Act
		lr := corestr.LeftRightFromSplit("nosep", "=")

		// Assert
		actual := args.Map{"result": lr.Left != "nosep"}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "LeftRightFromSplit Left returns full string -- no sep", actual)
	})
}

func Test_LeftRightFromSplit_LeftRightFromSplitTrimmed_FromS22(t *testing.T) {
	safeTest(t, "Test_LeftRightFromSplit_LeftRightFromSplitTrimmed_FromS22", func() {
		// Arrange & Act
		lr := corestr.LeftRightFromSplitTrimmed(" key = value ", "=")

		// Assert
		actual := args.Map{"result": lr.Left != "key"}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "LeftRightFromSplitTrimmed Left returns trimmed key", actual)
		actual = args.Map{"result": lr.Right != "value"}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "LeftRightFromSplitTrimmed Right returns trimmed value", actual)
	})
}

func Test_LeftRightFromSplit_LeftRightFromSplitFull_multi_sep_FromS22(t *testing.T) {
	safeTest(t, "Test_LeftRightFromSplit_LeftRightFromSplitFull_multi_sep_FromS22", func() {
		// Arrange & Act
		lr := corestr.LeftRightFromSplitFull("a:b:c:d", ":")

		// Assert
		actual := args.Map{"result": lr.Left != "a"}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "LeftRightFromSplitFull Left returns a", actual)
		actual = args.Map{"result": lr.Right != "b:c:d"}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "LeftRightFromSplitFull Right returns b:c:d", actual)
	})
}

func Test_LeftRightFromSplit_LeftRightFromSplitFullTrimmed_FromS22(t *testing.T) {
	safeTest(t, "Test_LeftRightFromSplit_LeftRightFromSplitFullTrimmed_FromS22", func() {
		// Arrange & Act
		lr := corestr.LeftRightFromSplitFullTrimmed(" a : b : c ", ":")

		// Assert
		actual := args.Map{"result": lr.Left != "a"}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "LeftRightFromSplitFullTrimmed Left returns trimmed a", actual)
		actual = args.Map{"result": lr.Right != "b : c"}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "LeftRightFromSplitFullTrimmed Right returns trimmed remainder", actual)
	})
}

func Test_LeftRightFromSplit_empty_FromS22(t *testing.T) {
	safeTest(t, "Test_LeftRightFromSplit_empty_FromS22", func() {
		// Arrange & Act
		lr := corestr.LeftRightFromSplit("", "=")

		// Assert
		actual := args.Map{"result": lr.Left != ""}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "LeftRightFromSplit Left returns empty -- empty input", actual)
	})
}


func Test_LRFromSplit_FromSeg1(t *testing.T) {
	safeTest(t, "Test_LRFromSplit_FromSeg1", func() {
		// Arrange
		lr := corestr.LeftRightFromSplit("key=value", "=")

		// Act
		actual := args.Map{
			"left": lr.Left,
			"right": lr.Right,
		}

		// Assert
		expected := args.Map{
			"left": "key",
			"right": "value",
		}
		expected.ShouldBeEqual(t, 0, "LeftRightFromSplit -- 2 parts", actual)
	})
}

func Test_LRFromSplitTrimmed_FromSeg1(t *testing.T) {
	safeTest(t, "Test_LRFromSplitTrimmed_FromSeg1", func() {
		// Arrange
		lr := corestr.LeftRightFromSplitTrimmed(" key = value ", "=")

		// Act
		actual := args.Map{
			"left": lr.Left,
			"right": lr.Right,
		}

		// Assert
		expected := args.Map{
			"left": "key",
			"right": "value",
		}
		expected.ShouldBeEqual(t, 0, "LeftRightFromSplitTrimmed -- trimmed", actual)
	})
}

func Test_LRFromSplitFull_FromSeg1(t *testing.T) {
	safeTest(t, "Test_LRFromSplitFull_FromSeg1", func() {
		// Arrange
		lr := corestr.LeftRightFromSplitFull("a:b:c:d", ":")

		// Act
		actual := args.Map{
			"left": lr.Left,
			"right": lr.Right,
		}

		// Assert
		expected := args.Map{
			"left": "a",
			"right": "b:c:d",
		}
		expected.ShouldBeEqual(t, 0, "LeftRightFromSplitFull -- remainder in right", actual)
	})
}

func Test_LRFromSplitFullTrimmed_FromSeg1(t *testing.T) {
	safeTest(t, "Test_LRFromSplitFullTrimmed_FromSeg1", func() {
		// Arrange
		lr := corestr.LeftRightFromSplitFullTrimmed(" a : b : c ", ":")

		// Act
		actual := args.Map{"left": lr.Left}

		// Assert
		expected := args.Map{"left": "a"}
		expected.ShouldBeEqual(t, 0, "LeftRightFromSplitFullTrimmed -- trimmed", actual)
	})
}

