// MIT License
// 
// Copyright (c) 2020–2026
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package corestrtests

// Auto-generated by Batch 2.2 split from S22_001_S22_FromSplit_Creators_test.go.
// See spec/01-app/29-corestrtests-phase2-merge-plan.md.

import (
	"testing"

	"github.com/alimtvnetwork/core/coredata/corestr"
	"github.com/alimtvnetwork/core/coretests/args"
)

func Test_LeftMiddleRightFromSplit_basic_FromS22(t *testing.T) {
	safeTest(t, "Test_LeftMiddleRightFromSplit_basic_FromS22", func() {
		// Arrange & Act
		lmr := corestr.LeftMiddleRightFromSplit("a.b.c", ".")

		// Assert
		actual := args.Map{"result": lmr.Left != "a"}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "LeftMiddleRightFromSplit Left returns a", actual)
		actual = args.Map{"result": lmr.Middle != "b"}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "LeftMiddleRightFromSplit Middle returns b", actual)
		actual = args.Map{"result": lmr.Right != "c"}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "LeftMiddleRightFromSplit Right returns c", actual)
	})
}

func Test_LeftMiddleRightFromSplit_no_sep_FromS22(t *testing.T) {
	safeTest(t, "Test_LeftMiddleRightFromSplit_no_sep_FromS22", func() {
		// Arrange & Act
		lmr := corestr.LeftMiddleRightFromSplit("nosep", ".")

		// Assert
		actual := args.Map{"result": lmr.Left != "nosep"}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "LeftMiddleRightFromSplit Left returns full string -- no sep", actual)
	})
}

func Test_LeftMiddleRightFromSplit_LeftMiddleRightFromSplitTrimmed_FromS22(t *testing.T) {
	safeTest(t, "Test_LeftMiddleRightFromSplit_LeftMiddleRightFromSplitTrimmed_FromS22", func() {
		// Arrange & Act
		lmr := corestr.LeftMiddleRightFromSplitTrimmed(" a . b . c ", ".")

		// Assert
		actual := args.Map{"result": lmr.Left != "a"}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "LeftMiddleRightFromSplitTrimmed Left returns trimmed a", actual)
		actual = args.Map{"result": lmr.Middle != "b"}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "LeftMiddleRightFromSplitTrimmed Middle returns trimmed b", actual)
		actual = args.Map{"result": lmr.Right != "c"}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "LeftMiddleRightFromSplitTrimmed Right returns trimmed c", actual)
	})
}

func Test_LeftMiddleRightFromSplit_LeftMiddleRightFromSplitN_FromS22(t *testing.T) {
	safeTest(t, "Test_LeftMiddleRightFromSplit_LeftMiddleRightFromSplitN_FromS22", func() {
		// Arrange & Act
		lmr := corestr.LeftMiddleRightFromSplitN("a:b:c:d:e", ":")

		// Assert
		actual := args.Map{"result": lmr.Left != "a"}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "LeftMiddleRightFromSplitN Left returns a", actual)
		actual = args.Map{"result": lmr.Middle != "b"}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "LeftMiddleRightFromSplitN Middle returns b", actual)
		actual = args.Map{"result": lmr.Right != "c:d:e"}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "LeftMiddleRightFromSplitN Right returns c:d:e", actual)
	})
}

func Test_LeftMiddleRightFromSplit_LeftMiddleRightFromSplitNTrimmed_FromS22(t *testing.T) {
	safeTest(t, "Test_LeftMiddleRightFromSplit_LeftMiddleRightFromSplitNTrimmed_FromS22", func() {
		// Arrange & Act
		lmr := corestr.LeftMiddleRightFromSplitNTrimmed(" a : b : c : d ", ":")

		// Assert
		actual := args.Map{"result": lmr.Left != "a"}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "LeftMiddleRightFromSplitNTrimmed Left returns trimmed a", actual)
		actual = args.Map{"result": lmr.Middle != "b"}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "LeftMiddleRightFromSplitNTrimmed Middle returns trimmed b", actual)
	})
}

func Test_LeftMiddleRightFromSplit_empty_FromS22(t *testing.T) {
	safeTest(t, "Test_LeftMiddleRightFromSplit_empty_FromS22", func() {
		// Arrange & Act
		lmr := corestr.LeftMiddleRightFromSplit("", ".")

		// Assert
		actual := args.Map{"result": lmr.Left != ""}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "LeftMiddleRightFromSplit Left returns empty -- empty input", actual)
	})
}


func Test_LMRFromSplit_FromSeg1(t *testing.T) {
	safeTest(t, "Test_LMRFromSplit_FromSeg1", func() {
		// Arrange
		lmr := corestr.LeftMiddleRightFromSplit("a:b:c", ":")

		// Act
		actual := args.Map{
			"left": lmr.Left,
			"mid": lmr.Middle,
			"right": lmr.Right,
		}

		// Assert
		expected := args.Map{
			"left": "a",
			"mid": "b",
			"right": "c",
		}
		expected.ShouldBeEqual(t, 0, "LeftMiddleRightFromSplit -- 3 parts", actual)
	})
}

func Test_LMRFromSplitTrimmed_FromSeg1(t *testing.T) {
	safeTest(t, "Test_LMRFromSplitTrimmed_FromSeg1", func() {
		// Arrange
		lmr := corestr.LeftMiddleRightFromSplitTrimmed(" a : b : c ", ":")

		// Act
		actual := args.Map{
			"left": lmr.Left,
			"mid": lmr.Middle,
			"right": lmr.Right,
		}

		// Assert
		expected := args.Map{
			"left": "a",
			"mid": "b",
			"right": "c",
		}
		expected.ShouldBeEqual(t, 0, "LeftMiddleRightFromSplitTrimmed -- trimmed", actual)
	})
}

func Test_LMRFromSplitN_FromSeg1(t *testing.T) {
	safeTest(t, "Test_LMRFromSplitN_FromSeg1", func() {
		// Arrange
		lmr := corestr.LeftMiddleRightFromSplitN("a:b:c:d:e", ":")

		// Act
		actual := args.Map{
			"left": lmr.Left,
			"mid": lmr.Middle,
			"right": lmr.Right,
		}

		// Assert
		expected := args.Map{
			"left": "a",
			"mid": "b",
			"right": "c:d:e",
		}
		expected.ShouldBeEqual(t, 0, "LeftMiddleRightFromSplitN -- remainder in right", actual)
	})
}

func Test_LMRFromSplitNTrimmed_FromSeg1(t *testing.T) {
	safeTest(t, "Test_LMRFromSplitNTrimmed_FromSeg1", func() {
		// Arrange
		lmr := corestr.LeftMiddleRightFromSplitNTrimmed(" a : b : c : d ", ":")

		// Act
		actual := args.Map{
			"left": lmr.Left,
			"mid": lmr.Middle,
		}

		// Assert
		expected := args.Map{
			"left": "a",
			"mid": "b",
		}
		expected.ShouldBeEqual(t, 0, "LeftMiddleRightFromSplitNTrimmed -- trimmed", actual)
	})
}

