// MIT License
// 
// Copyright (c) 2020–2026
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package corestrtests

// Auto-generated by Batch 2.2 split from S22_001_S22_FromSplit_Creators_test.go.
// See spec/01-app/29-corestrtests-phase2-merge-plan.md.

import (
	"testing"

	"github.com/alimtvnetwork/core-v8/coredata/corestr"
	"github.com/alimtvnetwork/core-v8/coretests/args"
)

func Test_NewCollection_Empty_FromS22(t *testing.T) {
	safeTest(t, "Test_NewCollection_Empty_FromS22", func() {
		// Act
		c := corestr.New.Collection.Empty()

		// Assert
		actual := args.Map{"result": c == nil || !c.IsEmpty()}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Collection.Empty returns empty collection", actual)
	})
}

func Test_NewCollection_Cap_FromS22(t *testing.T) {
	safeTest(t, "Test_NewCollection_Cap_FromS22", func() {
		// Act
		c := corestr.New.Collection.Cap(10)

		// Assert
		actual := args.Map{"result": c == nil || !c.IsEmpty()}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Collection.Cap returns empty collection with capacity", actual)
	})
}

func Test_NewCollection_CloneStrings_FromS22(t *testing.T) {
	safeTest(t, "Test_NewCollection_CloneStrings_FromS22", func() {
		// Arrange
		items := []string{"a", "b"}

		// Act
		c := corestr.New.Collection.CloneStrings(items)

		// Assert
		actual := args.Map{"result": c.Length() != 2}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Collection.CloneStrings returns 2 items", actual)
	})
}

func Test_NewCollection_Create_FromS22(t *testing.T) {
	safeTest(t, "Test_NewCollection_Create_FromS22", func() {
		// Act
		c := corestr.New.Collection.Create([]string{"x"})

		// Assert
		actual := args.Map{"result": c.Length() != 1}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Collection.Create returns 1 item", actual)
	})
}

func Test_NewCollection_StringsOptions_clone_FromS22(t *testing.T) {
	safeTest(t, "Test_NewCollection_StringsOptions_clone_FromS22", func() {
		// Act
		c := corestr.New.Collection.StringsOptions(true, []string{"a", "b"})

		// Assert
		actual := args.Map{"result": c.Length() != 2}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Collection.StringsOptions clone returns 2 items", actual)
	})
}

func Test_NewCollection_StringsOptions_no_clone_empty_FromS22(t *testing.T) {
	safeTest(t, "Test_NewCollection_StringsOptions_no_clone_empty_FromS22", func() {
		// Act
		c := corestr.New.Collection.StringsOptions(false, []string{})

		// Assert
		actual := args.Map{"result": c.IsEmpty()}
		expected := args.Map{"result": true}
		expected.ShouldBeEqual(t, 0, "New.Collection.StringsOptions no clone empty returns empty", actual)
	})
}

func Test_NewCollection_LineUsingSep_FromS22(t *testing.T) {
	safeTest(t, "Test_NewCollection_LineUsingSep_FromS22", func() {
		// Act
		c := corestr.New.Collection.LineUsingSep(",", "a,b,c")

		// Assert
		actual := args.Map{"result": c.Length() != 3}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Collection.LineUsingSep returns 3 items", actual)
	})
}

func Test_NewCollection_LineDefault_FromS22(t *testing.T) {
	safeTest(t, "Test_NewCollection_LineDefault_FromS22", func() {
		// Act
		c := corestr.New.Collection.LineDefault("a\nb\nc")

		// Assert
		actual := args.Map{"result": c.Length() != 3}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Collection.LineDefault returns 3 items", actual)
	})
}

func Test_NewCollection_StringsPlusCap_zero_cap_FromS22(t *testing.T) {
	safeTest(t, "Test_NewCollection_StringsPlusCap_zero_cap_FromS22", func() {
		// Act
		c := corestr.New.Collection.StringsPlusCap(0, []string{"a"})

		// Assert
		actual := args.Map{"result": c.Length() != 1}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Collection.StringsPlusCap returns 1 item", actual)
	})
}

func Test_NewCollection_StringsPlusCap_with_cap_FromS22(t *testing.T) {
	safeTest(t, "Test_NewCollection_StringsPlusCap_with_cap_FromS22", func() {
		// Act
		c := corestr.New.Collection.StringsPlusCap(5, []string{"a"})

		// Assert
		actual := args.Map{"result": c.Length() != 1}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Collection.StringsPlusCap returns 1 item", actual)
	})
}

func Test_NewCollection_CapStrings_zero_cap_FromS22(t *testing.T) {
	safeTest(t, "Test_NewCollection_CapStrings_zero_cap_FromS22", func() {
		// Act
		c := corestr.New.Collection.CapStrings(0, []string{"a"})

		// Assert
		actual := args.Map{"result": c.Length() != 1}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Collection.CapStrings returns 1 item", actual)
	})
}

func Test_NewCollection_CapStrings_with_cap_FromS22(t *testing.T) {
	safeTest(t, "Test_NewCollection_CapStrings_with_cap_FromS22", func() {
		// Act
		c := corestr.New.Collection.CapStrings(5, []string{"a"})

		// Assert
		actual := args.Map{"result": c.Length() != 1}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Collection.CapStrings returns 1 item", actual)
	})
}

func Test_NewCollection_LenCap_FromS22(t *testing.T) {
	safeTest(t, "Test_NewCollection_LenCap_FromS22", func() {
		// Act
		c := corestr.New.Collection.LenCap(3, 10)

		// Assert
		actual := args.Map{"result": c.Length() != 3}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Collection.LenCap returns 3 items", actual)
	})
}

