// MIT License
// 
// Copyright (c) 2020–2026
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package corestrtests

// Auto-generated by Batch 2.2 split from S22_001_S22_FromSplit_Creators_test.go.
// See spec/01-app/29-corestrtests-phase2-merge-plan.md.

import (
	"testing"

	"github.com/alimtvnetwork/core-v8/coredata/corestr"
	"github.com/alimtvnetwork/core-v8/coretests/args"
)

func Test_NewHashset_Empty_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashset_Empty_FromS22", func() {
		// Act
		hs := corestr.New.Hashset.Empty()

		// Assert
		actual := args.Map{"result": hs == nil || hs.Length() != 0}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Hashset.Empty returns empty hashset", actual)
	})
}

func Test_NewHashset_Cap_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashset_Cap_FromS22", func() {
		// Act
		hs := corestr.New.Hashset.Cap(10)

		// Assert
		actual := args.Map{"result": hs == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Hashset.Cap returns non-nil", actual)
	})
}

func Test_NewHashset_Strings_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashset_Strings_FromS22", func() {
		// Act
		hs := corestr.New.Hashset.Strings([]string{"a", "b", "a"})

		// Assert
		actual := args.Map{"result": hs.Length() != 2}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Hashset.Strings returns 2 unique items", actual)
	})
}

func Test_NewHashset_Strings_empty_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashset_Strings_empty_FromS22", func() {
		// Act
		hs := corestr.New.Hashset.Strings([]string{})

		// Assert
		actual := args.Map{"result": hs.Length() != 0}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Hashset.Strings returns 0 -- empty input", actual)
	})
}

func Test_NewHashset_StringsSpreadItems_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashset_StringsSpreadItems_FromS22", func() {
		// Act
		hs := corestr.New.Hashset.StringsSpreadItems("x", "y")

		// Assert
		actual := args.Map{"result": hs.Length() != 2}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Hashset.StringsSpreadItems returns 2", actual)
	})
}

func Test_NewHashset_StringsSpreadItems_empty_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashset_StringsSpreadItems_empty_FromS22", func() {
		// Act
		hs := corestr.New.Hashset.StringsSpreadItems()

		// Assert
		actual := args.Map{"result": hs.Length() != 0}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Hashset.StringsSpreadItems returns 0 -- empty", actual)
	})
}

func Test_NewHashset_StringsOption_nil_zero_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashset_StringsOption_nil_zero_FromS22", func() {
		// Act
		hs := corestr.New.Hashset.StringsOption(0, false)

		// Assert
		actual := args.Map{"result": hs == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Hashset.StringsOption returns non-nil -- nil items zero cap", actual)
	})
}

func Test_NewHashset_StringsOption_nil_with_cap_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashset_StringsOption_nil_with_cap_FromS22", func() {
		// Act
		hs := corestr.New.Hashset.StringsOption(5, false)

		// Assert
		actual := args.Map{"result": hs == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Hashset.StringsOption returns non-nil -- nil items with cap", actual)
	})
}

func Test_NewHashset_UsingCollection_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashset_UsingCollection_FromS22", func() {
		// Arrange
		col := corestr.New.Collection.Strings([]string{"a", "b"})

		// Act
		hs := corestr.New.Hashset.UsingCollection(col)

		// Assert
		actual := args.Map{"result": hs.Length() != 2}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Hashset.UsingCollection returns 2", actual)
	})
}

func Test_NewHashset_UsingCollection_nil_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashset_UsingCollection_nil_FromS22", func() {
		// Act
		hs := corestr.New.Hashset.UsingCollection(nil)

		// Assert
		actual := args.Map{"result": hs.Length() != 0}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Hashset.UsingCollection returns empty -- nil input", actual)
	})
}

func Test_NewHashset_SimpleSlice_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashset_SimpleSlice_FromS22", func() {
		// Arrange
		ss := corestr.New.SimpleSlice.Strings([]string{"a", "b"})

		// Act
		hs := corestr.New.Hashset.SimpleSlice(ss)

		// Assert
		actual := args.Map{"result": hs.Length() != 2}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Hashset.SimpleSlice returns 2", actual)
	})
}

func Test_NewHashset_UsingMap_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashset_UsingMap_FromS22", func() {
		// Act
		hs := corestr.New.Hashset.UsingMap(map[string]bool{"a": true, "b": true})

		// Assert
		actual := args.Map{"result": hs.Length() != 2}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Hashset.UsingMap returns 2", actual)
	})
}

func Test_NewHashset_UsingMap_empty_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashset_UsingMap_empty_FromS22", func() {
		// Act
		hs := corestr.New.Hashset.UsingMap(map[string]bool{})

		// Assert
		actual := args.Map{"result": hs.Length() != 0}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Hashset.UsingMap returns empty -- empty map", actual)
	})
}

func Test_NewHashset_UsingMapOption_clone_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashset_UsingMapOption_clone_FromS22", func() {
		// Act
		hs := corestr.New.Hashset.UsingMapOption(0, true, map[string]bool{"a": true})

		// Assert
		actual := args.Map{"result": hs.Length() != 1}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Hashset.UsingMapOption clone returns 1", actual)
	})
}

func Test_NewHashset_UsingMapOption_no_clone_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashset_UsingMapOption_no_clone_FromS22", func() {
		// Act
		hs := corestr.New.Hashset.UsingMapOption(0, false, map[string]bool{"a": true})

		// Assert
		actual := args.Map{"result": hs.Length() != 1}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Hashset.UsingMapOption no clone returns 1", actual)
	})
}

func Test_NewHashset_UsingMapOption_empty_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashset_UsingMapOption_empty_FromS22", func() {
		// Act
		hs := corestr.New.Hashset.UsingMapOption(5, false, map[string]bool{})

		// Assert
		actual := args.Map{"result": hs == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Hashset.UsingMapOption returns non-nil -- empty map with cap", actual)
	})
}

