package corestrtests

// Auto-generated by Batch 2.2 split from S22_001_S22_FromSplit_Creators_test.go.
// See spec/01-app/29-corestrtests-phase2-merge-plan.md.

import (
	"testing"

	"github.com/alimtvnetwork/core/coredata/corestr"
	"github.com/alimtvnetwork/core/coretests/args"
)

func Test_NewHashmap_Empty_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_Empty_FromS22", func() {
		// Act
		hm := corestr.New.Hashmap.Empty()

		// Assert
		actual := args.Map{"result": hm == nil || hm.Length() != 0}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Hashmap.Empty returns empty hashmap", actual)
	})
}

func Test_NewHashmap_Cap_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_Cap_FromS22", func() {
		// Act
		hm := corestr.New.Hashmap.Cap(10)

		// Assert
		actual := args.Map{"result": hm == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Hashmap.Cap returns non-nil", actual)
	})
}

func Test_NewHashmap_UsingMap_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_UsingMap_FromS22", func() {
		// Act
		hm := corestr.New.Hashmap.UsingMap(map[string]string{"a": "1"})

		// Assert
		actual := args.Map{"result": hm.Length() != 1}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Hashmap.UsingMap returns 1", actual)
	})
}

func Test_NewHashmap_UsingMapOptions_clone_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_UsingMapOptions_clone_FromS22", func() {
		// Act
		hm := corestr.New.Hashmap.UsingMapOptions(true, 0, map[string]string{"a": "1"})

		// Assert
		actual := args.Map{"result": hm.Length() != 1}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Hashmap.UsingMapOptions clone returns 1", actual)
	})
}

func Test_NewHashmap_UsingMapOptions_no_clone_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_UsingMapOptions_no_clone_FromS22", func() {
		// Act
		hm := corestr.New.Hashmap.UsingMapOptions(false, 0, map[string]string{"a": "1"})

		// Assert
		actual := args.Map{"result": hm.Length() != 1}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Hashmap.UsingMapOptions no clone returns 1", actual)
	})
}

func Test_NewHashmap_UsingMapOptions_empty_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_UsingMapOptions_empty_FromS22", func() {
		// Act
		hm := corestr.New.Hashmap.UsingMapOptions(true, 5, map[string]string{})

		// Assert
		actual := args.Map{"result": hm == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Hashmap.UsingMapOptions returns non-nil -- empty with cap", actual)
	})
}

func Test_NewHashmap_MapWithCap_zero_cap_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_MapWithCap_zero_cap_FromS22", func() {
		// Act
		hm := corestr.New.Hashmap.MapWithCap(0, map[string]string{"a": "1"})

		// Assert
		actual := args.Map{"result": hm.Length() != 1}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Hashmap.MapWithCap returns 1", actual)
	})
}

func Test_NewHashmap_MapWithCap_with_cap_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_MapWithCap_with_cap_FromS22", func() {
		// Act
		hm := corestr.New.Hashmap.MapWithCap(5, map[string]string{"a": "1"})

		// Assert
		actual := args.Map{"result": hm.Length() != 1}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Hashmap.MapWithCap returns 1", actual)
	})
}

func Test_NewHashmap_MapWithCap_empty_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_MapWithCap_empty_FromS22", func() {
		// Act
		hm := corestr.New.Hashmap.MapWithCap(5, map[string]string{})

		// Assert
		actual := args.Map{"result": hm == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Hashmap.MapWithCap returns non-nil -- empty with cap", actual)
	})
}

func Test_NewHashmap_KeyValues_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_KeyValues_FromS22", func() {
		// Act
		hm := corestr.New.Hashmap.KeyValues(corestr.KeyValuePair{Key: "a", Value: "1"})

		// Assert
		actual := args.Map{"result": hm.Length() != 1}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Hashmap.KeyValues returns 1", actual)
	})
}

func Test_NewHashmap_KeyValues_empty_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_KeyValues_empty_FromS22", func() {
		// Act
		hm := corestr.New.Hashmap.KeyValues()

		// Assert
		actual := args.Map{"result": hm == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Hashmap.KeyValues returns non-nil -- empty", actual)
	})
}

func Test_NewHashmap_KeyAnyValues_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_KeyAnyValues_FromS22", func() {
		// Act
		hm := corestr.New.Hashmap.KeyAnyValues(corestr.KeyAnyValuePair{Key: "a", Value: "1"})

		// Assert
		actual := args.Map{"result": hm.Length() != 1}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Hashmap.KeyAnyValues returns 1", actual)
	})
}

func Test_NewHashmap_KeyAnyValues_empty_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_KeyAnyValues_empty_FromS22", func() {
		// Act
		hm := corestr.New.Hashmap.KeyAnyValues()

		// Assert
		actual := args.Map{"result": hm == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Hashmap.KeyAnyValues returns non-nil -- empty", actual)
	})
}

func Test_NewHashmap_KeyValuesCollection_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_KeyValuesCollection_FromS22", func() {
		// Arrange
		keys := corestr.New.Collection.Strings([]string{"a", "b"})
		vals := corestr.New.Collection.Strings([]string{"1", "2"})

		// Act
		hm := corestr.New.Hashmap.KeyValuesCollection(keys, vals)

		// Assert
		actual := args.Map{"result": hm.Length() != 2}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Hashmap.KeyValuesCollection returns 2", actual)
	})
}

func Test_NewHashmap_KeyValuesCollection_nil_keys_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_KeyValuesCollection_nil_keys_FromS22", func() {
		// Act
		hm := corestr.New.Hashmap.KeyValuesCollection(nil, nil)

		// Assert
		actual := args.Map{"result": hm.Length() != 0}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Hashmap.KeyValuesCollection returns empty -- nil keys", actual)
	})
}

func Test_NewHashmap_KeyValuesStrings_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_KeyValuesStrings_FromS22", func() {
		// Act
		hm := corestr.New.Hashmap.KeyValuesStrings([]string{"a"}, []string{"1"})

		// Assert
		actual := args.Map{"result": hm.Length() != 1}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Hashmap.KeyValuesStrings returns 1", actual)
	})
}

func Test_NewHashmap_KeyValuesStrings_empty_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_KeyValuesStrings_empty_FromS22", func() {
		// Act
		hm := corestr.New.Hashmap.KeyValuesStrings([]string{}, []string{})

		// Assert
		actual := args.Map{"result": hm.Length() != 0}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.Hashmap.KeyValuesStrings returns empty -- empty keys", actual)
	})
}

func Test_NewHashmap_NewLinkedList_Create_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewLinkedList_Create_FromS22", func() {
		// Act
		ll := corestr.New.LinkedList.Create()

		// Assert
		actual := args.Map{"result": ll == nil || ll.Length() != 0}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.LinkedList.Create returns empty list", actual)
	})
}

func Test_NewHashmap_NewLinkedList_Strings_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewLinkedList_Strings_FromS22", func() {
		// Act
		ll := corestr.New.LinkedList.Strings([]string{"a", "b"})

		// Assert
		actual := args.Map{"result": ll.Length() != 2}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.LinkedList.Strings returns 2", actual)
	})
}

func Test_NewHashmap_NewLinkedList_Strings_empty_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewLinkedList_Strings_empty_FromS22", func() {
		// Act
		ll := corestr.New.LinkedList.Strings([]string{})

		// Assert
		actual := args.Map{"result": ll.Length() != 0}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.LinkedList.Strings returns empty -- empty input", actual)
	})
}

func Test_NewHashmap_NewLinkedList_SpreadStrings_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewLinkedList_SpreadStrings_FromS22", func() {
		// Act
		ll := corestr.New.LinkedList.SpreadStrings("x", "y", "z")

		// Assert
		actual := args.Map{"result": ll.Length() != 3}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.LinkedList.SpreadStrings returns 3", actual)
	})
}

func Test_NewHashmap_NewLinkedList_SpreadStrings_empty_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewLinkedList_SpreadStrings_empty_FromS22", func() {
		// Act
		ll := corestr.New.LinkedList.SpreadStrings()

		// Assert
		actual := args.Map{"result": ll.Length() != 0}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.LinkedList.SpreadStrings returns empty -- no args", actual)
	})
}

func Test_NewHashmap_NewLinkedList_UsingMap_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewLinkedList_UsingMap_FromS22", func() {
		// Act
		ll := corestr.New.LinkedList.UsingMap(map[string]bool{"a": true, "b": true})

		// Assert
		actual := args.Map{"result": ll.Length() != 2}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.LinkedList.UsingMap returns 2", actual)
	})
}

func Test_NewHashmap_NewLinkedList_UsingMap_nil_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewLinkedList_UsingMap_nil_FromS22", func() {
		// Act
		ll := corestr.New.LinkedList.UsingMap(nil)

		// Assert
		actual := args.Map{"result": ll.Length() != 0}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.LinkedList.UsingMap returns empty -- nil input", actual)
	})
}

func Test_NewHashmap_NewLinkedCollection_Create_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewLinkedCollection_Create_FromS22", func() {
		// Act
		lc := corestr.New.LinkedCollection.Create()

		// Assert
		actual := args.Map{"result": lc == nil || lc.Length() != 0}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.LinkedCollection.Create returns empty", actual)
	})
}

func Test_NewHashmap_NewLinkedCollection_Empty_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewLinkedCollection_Empty_FromS22", func() {
		// Act
		lc := corestr.New.LinkedCollection.Empty()

		// Assert
		actual := args.Map{"result": lc == nil || lc.Length() != 0}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.LinkedCollection.Empty returns empty", actual)
	})
}

func Test_NewHashmap_NewLinkedCollection_UsingCollections_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewLinkedCollection_UsingCollections_FromS22", func() {
		// Arrange
		col1 := corestr.New.Collection.Strings([]string{"a"})
		col2 := corestr.New.Collection.Strings([]string{"b"})

		// Act
		lc := corestr.New.LinkedCollection.UsingCollections(col1, col2)

		// Assert
		actual := args.Map{"result": lc.Length() != 2}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.LinkedCollection.UsingCollections returns 2", actual)
	})
}

func Test_NewHashmap_NewLinkedCollection_UsingCollections_nil_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewLinkedCollection_UsingCollections_nil_FromS22", func() {
		// Act
		lc := corestr.New.LinkedCollection.UsingCollections()

		// Assert
		actual := args.Map{"result": lc.Length() != 0}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.LinkedCollection.UsingCollections returns empty -- nil", actual)
	})
}

func Test_NewHashmap_NewLinkedCollection_Strings_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewLinkedCollection_Strings_FromS22", func() {
		// Act
		lc := corestr.New.LinkedCollection.Strings("a", "b")

		// Assert — Strings bundles all items into a single collection node
		actual := args.Map{"result": lc.Length() != 1}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.LinkedCollection.Strings returns 1 node", actual)
	})
}

func Test_NewHashmap_NewLinkedCollection_Strings_empty_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewLinkedCollection_Strings_empty_FromS22", func() {
		// Act
		lc := corestr.New.LinkedCollection.Strings()

		// Assert
		actual := args.Map{"result": lc.Length() != 0}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.LinkedCollection.Strings returns empty -- no args", actual)
	})
}

func Test_NewHashmap_NewKeyValues_Empty_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewKeyValues_Empty_FromS22", func() {
		// Act
		kvc := corestr.New.KeyValues.Empty()

		// Assert
		actual := args.Map{"result": kvc == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.KeyValues.Empty returns non-nil", actual)
	})
}

func Test_NewHashmap_NewKeyValues_Cap_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewKeyValues_Cap_FromS22", func() {
		// Act
		kvc := corestr.New.KeyValues.Cap(10)

		// Assert
		actual := args.Map{"result": kvc == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.KeyValues.Cap returns non-nil", actual)
	})
}

func Test_NewHashmap_NewKeyValues_UsingMap_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewKeyValues_UsingMap_FromS22", func() {
		// Act
		kvc := corestr.New.KeyValues.UsingMap(map[string]string{"a": "1"})

		// Assert
		actual := args.Map{"result": kvc.Length() != 1}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.KeyValues.UsingMap returns 1", actual)
	})
}

func Test_NewHashmap_NewKeyValues_UsingMap_empty_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewKeyValues_UsingMap_empty_FromS22", func() {
		// Act
		kvc := corestr.New.KeyValues.UsingMap(map[string]string{})

		// Assert
		actual := args.Map{"result": kvc.Length() != 0}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.KeyValues.UsingMap returns empty -- empty map", actual)
	})
}

func Test_NewHashmap_NewKeyValues_UsingKeyValuePairs_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewKeyValues_UsingKeyValuePairs_FromS22", func() {
		// Act
		kvc := corestr.New.KeyValues.UsingKeyValuePairs(
			corestr.KeyValuePair{Key: "a", Value: "1"},
		)

		// Assert
		actual := args.Map{"result": kvc.Length() != 1}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.KeyValues.UsingKeyValuePairs returns 1", actual)
	})
}

func Test_NewHashmap_NewKeyValues_UsingKeyValuePairs_empty_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewKeyValues_UsingKeyValuePairs_empty_FromS22", func() {
		// Act
		kvc := corestr.New.KeyValues.UsingKeyValuePairs()

		// Assert
		actual := args.Map{"result": kvc.Length() != 0}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.KeyValues.UsingKeyValuePairs returns empty -- no args", actual)
	})
}

func Test_NewHashmap_NewKeyValues_UsingKeyValueStrings_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewKeyValues_UsingKeyValueStrings_FromS22", func() {
		// Act
		kvc := corestr.New.KeyValues.UsingKeyValueStrings(
			[]string{"a", "b"},
			[]string{"1", "2"},
		)

		// Assert
		actual := args.Map{"result": kvc.Length() != 2}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.KeyValues.UsingKeyValueStrings returns 2", actual)
	})
}

func Test_NewHashmap_NewKeyValues_UsingKeyValueStrings_empty_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewKeyValues_UsingKeyValueStrings_empty_FromS22", func() {
		// Act
		kvc := corestr.New.KeyValues.UsingKeyValueStrings([]string{}, []string{})

		// Assert
		actual := args.Map{"result": kvc.Length() != 0}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.KeyValues.UsingKeyValueStrings returns empty -- empty input", actual)
	})
}

func Test_NewHashmap_NewHashsetsCollection_Empty_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewHashsetsCollection_Empty_FromS22", func() {
		// Act
		hsc := corestr.New.HashsetsCollection.Empty()

		// Assert
		actual := args.Map{"result": hsc == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.HashsetsCollection.Empty returns non-nil", actual)
	})
}

func Test_NewHashmap_NewHashsetsCollection_Cap_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewHashsetsCollection_Cap_FromS22", func() {
		// Act
		hsc := corestr.New.HashsetsCollection.Cap(5)

		// Assert
		actual := args.Map{"result": hsc == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.HashsetsCollection.Cap returns non-nil", actual)
	})
}

func Test_NewHashmap_NewHashsetsCollection_LenCap_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewHashsetsCollection_LenCap_FromS22", func() {
		// Act
		hsc := corestr.New.HashsetsCollection.LenCap(0, 5)

		// Assert
		actual := args.Map{"result": hsc == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.HashsetsCollection.LenCap returns non-nil", actual)
	})
}

func Test_NewHashmap_NewHashsetsCollection_UsingHashsets_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewHashsetsCollection_UsingHashsets_FromS22", func() {
		// Arrange
		hs := *corestr.New.Hashset.StringsSpreadItems("a", "b")

		// Act
		hsc := corestr.New.HashsetsCollection.UsingHashsets(hs)

		// Assert
		actual := args.Map{"result": hsc == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.HashsetsCollection.UsingHashsets returns non-nil", actual)
	})
}

func Test_NewHashmap_NewHashsetsCollection_UsingHashsets_empty_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewHashsetsCollection_UsingHashsets_empty_FromS22", func() {
		// Act
		hsc := corestr.New.HashsetsCollection.UsingHashsets()

		// Assert
		actual := args.Map{"result": hsc == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.HashsetsCollection.UsingHashsets returns non-nil -- empty", actual)
	})
}

func Test_NewHashmap_NewHashsetsCollection_UsingHashsetsPointers_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewHashsetsCollection_UsingHashsetsPointers_FromS22", func() {
		// Arrange
		hs := corestr.New.Hashset.StringsSpreadItems("a")

		// Act
		hsc := corestr.New.HashsetsCollection.UsingHashsetsPointers(hs)

		// Assert
		actual := args.Map{"result": hsc == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.HashsetsCollection.UsingHashsetsPointers returns non-nil", actual)
	})
}

func Test_NewHashmap_NewHashsetsCollection_UsingHashsetsPointers_empty_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewHashsetsCollection_UsingHashsetsPointers_empty_FromS22", func() {
		// Act
		hsc := corestr.New.HashsetsCollection.UsingHashsetsPointers()

		// Assert
		actual := args.Map{"result": hsc == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.HashsetsCollection.UsingHashsetsPointers returns non-nil -- empty", actual)
	})
}

func Test_NewHashmap_NewCollectionsOfCollection_Empty_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewCollectionsOfCollection_Empty_FromS22", func() {
		// Act
		coc := corestr.New.CollectionsOfCollection.Empty()

		// Assert
		actual := args.Map{"result": coc == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.CollectionsOfCollection.Empty returns non-nil", actual)
	})
}

func Test_NewHashmap_NewCollectionsOfCollection_Cap_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewCollectionsOfCollection_Cap_FromS22", func() {
		// Act
		coc := corestr.New.CollectionsOfCollection.Cap(5)

		// Assert
		actual := args.Map{"result": coc == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.CollectionsOfCollection.Cap returns non-nil", actual)
	})
}

func Test_NewHashmap_NewCollectionsOfCollection_LenCap_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewCollectionsOfCollection_LenCap_FromS22", func() {
		// Act
		coc := corestr.New.CollectionsOfCollection.LenCap(0, 5)

		// Assert
		actual := args.Map{"result": coc == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.CollectionsOfCollection.LenCap returns non-nil", actual)
	})
}

func Test_NewHashmap_NewCollectionsOfCollection_Strings_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewCollectionsOfCollection_Strings_FromS22", func() {
		// Act
		coc := corestr.New.CollectionsOfCollection.Strings([]string{"a", "b"})

		// Assert
		actual := args.Map{"result": coc == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.CollectionsOfCollection.Strings returns non-nil", actual)
	})
}

func Test_NewHashmap_NewCollectionsOfCollection_CloneStrings_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewCollectionsOfCollection_CloneStrings_FromS22", func() {
		// Act
		coc := corestr.New.CollectionsOfCollection.CloneStrings([]string{"a"})

		// Assert
		actual := args.Map{"result": coc == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.CollectionsOfCollection.CloneStrings returns non-nil", actual)
	})
}

func Test_NewHashmap_NewCollectionsOfCollection_SpreadStrings_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewCollectionsOfCollection_SpreadStrings_FromS22", func() {
		// Act
		coc := corestr.New.CollectionsOfCollection.SpreadStrings(true, "a", "b")

		// Assert
		actual := args.Map{"result": coc == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.CollectionsOfCollection.SpreadStrings returns non-nil", actual)
	})
}

func Test_NewHashmap_NewCollectionsOfCollection_StringsOption_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewCollectionsOfCollection_StringsOption_FromS22", func() {
		// Act
		coc := corestr.New.CollectionsOfCollection.StringsOption(true, 5, []string{"a"})

		// Assert
		actual := args.Map{"result": coc == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.CollectionsOfCollection.StringsOption returns non-nil", actual)
	})
}

func Test_NewHashmap_NewCollectionsOfCollection_StringsOptions_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewCollectionsOfCollection_StringsOptions_FromS22", func() {
		// Act
		coc := corestr.New.CollectionsOfCollection.StringsOptions(false, 5, []string{"a"})

		// Assert
		actual := args.Map{"result": coc == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.CollectionsOfCollection.StringsOptions returns non-nil", actual)
	})
}

func Test_NewHashmap_NewCollectionsOfCollection_StringsOfStrings_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewCollectionsOfCollection_StringsOfStrings_FromS22", func() {
		// Act
		coc := corestr.New.CollectionsOfCollection.StringsOfStrings(
			true,
			[]string{"a", "b"},
			[]string{"c", "d"},
		)

		// Assert
		actual := args.Map{"result": coc == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.CollectionsOfCollection.StringsOfStrings returns non-nil", actual)
	})
}

func Test_NewHashmap_NewSSO_Init_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewSSO_Init_FromS22", func() {
		// Act
		sso := corestr.New.SimpleStringOnce.Init("hello")

		// Assert
		actual := args.Map{"result": sso.Value() != "hello"}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.SimpleStringOnce.Init returns hello", actual)
		actual = args.Map{"result": sso.IsInitialized()}
		expected = args.Map{"result": true}
		expected.ShouldBeEqual(t, 0, "New.SimpleStringOnce.Init returns initialized", actual)
	})
}

func Test_NewHashmap_NewSSO_InitPtr_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewSSO_InitPtr_FromS22", func() {
		// Act
		sso := corestr.New.SimpleStringOnce.InitPtr("world")

		// Assert
		actual := args.Map{"result": sso == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.SimpleStringOnce.InitPtr returns non-nil", actual)
		actual = args.Map{"result": sso.Value() != "world"}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.SimpleStringOnce.InitPtr returns world", actual)
	})
}

func Test_NewHashmap_NewSSO_Uninitialized_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewSSO_Uninitialized_FromS22", func() {
		// Act
		sso := corestr.New.SimpleStringOnce.Uninitialized("test")

		// Assert
		actual := args.Map{"result": sso.IsInitialized()}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.SimpleStringOnce.Uninitialized returns not initialized", actual)
	})
}

func Test_NewHashmap_NewSSO_Create_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewSSO_Create_FromS22", func() {
		// Act
		sso := corestr.New.SimpleStringOnce.Create("val", true)

		// Assert
		actual := args.Map{"result": sso.Value() != "val"}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.SimpleStringOnce.Create returns val", actual)
	})
}

func Test_NewHashmap_NewSSO_CreatePtr_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewSSO_CreatePtr_FromS22", func() {
		// Act
		sso := corestr.New.SimpleStringOnce.CreatePtr("val", false)

		// Assert
		actual := args.Map{"result": sso == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.SimpleStringOnce.CreatePtr returns non-nil", actual)
	})
}

func Test_NewHashmap_NewSSO_Empty_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewSSO_Empty_FromS22", func() {
		// Act
		sso := corestr.New.SimpleStringOnce.Empty()

		// Assert
		actual := args.Map{"result": sso.Value() != ""}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.SimpleStringOnce.Empty returns empty value", actual)
	})
}

func Test_NewHashmap_NewSSO_Any_no_field_names_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewSSO_Any_no_field_names_FromS22", func() {
		// Act
		sso := corestr.New.SimpleStringOnce.Any(false, 42, true)

		// Assert
		actual := args.Map{"result": sso.Value() == ""}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.SimpleStringOnce.Any returns non-empty -- int input", actual)
		actual = args.Map{"result": sso.IsInitialized()}
		expected = args.Map{"result": true}
		expected.ShouldBeEqual(t, 0, "New.SimpleStringOnce.Any returns initialized -- isInit true", actual)
	})
}

func Test_NewHashmap_NewSSO_Any_with_field_names_FromS22(t *testing.T) {
	safeTest(t, "Test_NewHashmap_NewSSO_Any_with_field_names_FromS22", func() {
		// Act
		sso := corestr.New.SimpleStringOnce.Any(true, "test", false)

		// Assert
		actual := args.Map{"result": sso.IsInitialized()}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "New.SimpleStringOnce.Any returns not initialized -- isInit false", actual)
	})
}
