// MIT License
// 
// Copyright (c) 2020–2026
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package corestrtests

// Auto-generated by Batch 2.2 split from S20_001_S20_NonChainedNodes_HashmapDiff_test.go.
// See spec/01-app/29-corestrtests-phase2-merge-plan.md.

import (
	"testing"

	"github.com/alimtvnetwork/core-v8/coredata/corestr"
	"github.com/alimtvnetwork/core-v8/coretests/args"
)

func Test_NonChainedLinkedCollectionNodes_NewNonChainedLinkedCollectionNodes_creates_FromS20(t *testing.T) {
	safeTest(t, "Test_NonChainedLinkedCollectionNodes_NewNonChainedLinkedCollectionNodes_creates_FromS20", func() {
		// Arrange & Act
		nodes := corestr.NewNonChainedLinkedCollectionNodes(5)

		// Assert
		actual := args.Map{"result": nodes == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "NewNonChainedLinkedCollectionNodes returns non-nil -- capacity 5", actual)
		actual = args.Map{"result": nodes.Length() != 0}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Length returns 0 -- empty", actual)
		actual = args.Map{"result": nodes.IsEmpty()}
		expected = args.Map{"result": true}
		expected.ShouldBeEqual(t, 0, "IsEmpty returns true -- no items", actual)
	})
}

func Test_NonChainedLinkedCollectionNodes_Adds_FromS20(t *testing.T) {
	safeTest(t, "Test_NonChainedLinkedCollectionNodes_Adds_FromS20", func() {
		// Arrange
		nodes := corestr.NewNonChainedLinkedCollectionNodes(5)
		col := corestr.New.Collection.Strings([]string{"a", "b"})
		lc := corestr.New.LinkedCollection.UsingCollections(col)
		head := lc.Head()

		// Act
		nodes.Adds(head)

		// Assert
		actual := args.Map{"result": nodes.Length() != 1}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Length returns 1 -- one node", actual)
		actual = args.Map{"result": nodes.HasItems()}
		expected = args.Map{"result": true}
		expected.ShouldBeEqual(t, 0, "HasItems returns true -- has items", actual)
	})
}

func Test_NonChainedLinkedCollectionNodes_Adds_nil_FromS20(t *testing.T) {
	safeTest(t, "Test_NonChainedLinkedCollectionNodes_Adds_nil_FromS20", func() {
		// Arrange
		nodes := corestr.NewNonChainedLinkedCollectionNodes(5)

		// Act
		result := nodes.Adds(nil...)

		// Assert
		actual := args.Map{"result": result != nodes}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Adds returns self -- nil input", actual)
	})
}

func Test_NonChainedLinkedCollectionNodes_FirstOrDefault_empty_FromS20(t *testing.T) {
	safeTest(t, "Test_NonChainedLinkedCollectionNodes_FirstOrDefault_empty_FromS20", func() {
		// Arrange
		nodes := corestr.NewNonChainedLinkedCollectionNodes(5)

		// Act
		result := nodes.FirstOrDefault()

		// Assert
		actual := args.Map{"result": result != nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "FirstOrDefault returns nil -- empty", actual)
	})
}

func Test_NonChainedLinkedCollectionNodes_LastOrDefault_empty_FromS20(t *testing.T) {
	safeTest(t, "Test_NonChainedLinkedCollectionNodes_LastOrDefault_empty_FromS20", func() {
		// Arrange
		nodes := corestr.NewNonChainedLinkedCollectionNodes(5)

		// Act
		result := nodes.LastOrDefault()

		// Assert
		actual := args.Map{"result": result != nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "LastOrDefault returns nil -- empty", actual)
	})
}

func Test_NonChainedLinkedCollectionNodes_First_Last_FromS20(t *testing.T) {
	safeTest(t, "Test_NonChainedLinkedCollectionNodes_First_Last_FromS20", func() {
		// Arrange
		nodes := corestr.NewNonChainedLinkedCollectionNodes(5)
		col1 := corestr.New.Collection.Strings([]string{"a"})
		col2 := corestr.New.Collection.Strings([]string{"b"})
		lc1 := corestr.New.LinkedCollection.UsingCollections(col1)
		lc2 := corestr.New.LinkedCollection.UsingCollections(col2)

		// Act
		nodes.Adds(lc1.Head(), lc2.Head())

		// Assert
		actual := args.Map{"result": nodes.First().Element.List()[0] != "a"}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "First returns collection with a", actual)
		actual = args.Map{"result": nodes.Last().Element.List()[0] != "b"}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Last returns collection with b", actual)
	})
}

func Test_NonChainedLinkedCollectionNodes_FirstOrDefault_has_items_FromS20(t *testing.T) {
	safeTest(t, "Test_NonChainedLinkedCollectionNodes_FirstOrDefault_has_items_FromS20", func() {
		// Arrange
		nodes := corestr.NewNonChainedLinkedCollectionNodes(5)
		col := corestr.New.Collection.Strings([]string{"x"})
		lc := corestr.New.LinkedCollection.UsingCollections(col)
		nodes.Adds(lc.Head())

		// Act
		result := nodes.FirstOrDefault()

		// Assert
		actual := args.Map{"result": result == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "FirstOrDefault returns non-nil -- has items", actual)
	})
}

func Test_NonChainedLinkedCollectionNodes_LastOrDefault_has_items_FromS20(t *testing.T) {
	safeTest(t, "Test_NonChainedLinkedCollectionNodes_LastOrDefault_has_items_FromS20", func() {
		// Arrange
		nodes := corestr.NewNonChainedLinkedCollectionNodes(5)
		col := corestr.New.Collection.Strings([]string{"x"})
		lc := corestr.New.LinkedCollection.UsingCollections(col)
		nodes.Adds(lc.Head())

		// Act
		result := nodes.LastOrDefault()

		// Assert
		actual := args.Map{"result": result == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "LastOrDefault returns non-nil -- has items", actual)
	})
}

func Test_NonChainedLinkedCollectionNodes_IsChainingApplied_false_FromS20(t *testing.T) {
	safeTest(t, "Test_NonChainedLinkedCollectionNodes_IsChainingApplied_false_FromS20", func() {
		// Arrange
		nodes := corestr.NewNonChainedLinkedCollectionNodes(5)

		// Act & Assert
		actual := args.Map{"result": nodes.IsChainingApplied()}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "IsChainingApplied returns false -- not applied", actual)
	})
}

func Test_NonChainedLinkedCollectionNodes_ApplyChaining_empty_FromS20(t *testing.T) {
	safeTest(t, "Test_NonChainedLinkedCollectionNodes_ApplyChaining_empty_FromS20", func() {
		// Arrange
		nodes := corestr.NewNonChainedLinkedCollectionNodes(5)

		// Act
		result := nodes.ApplyChaining()

		// Assert
		actual := args.Map{"result": result != nodes}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "ApplyChaining returns self -- empty", actual)
		actual = args.Map{"result": nodes.IsChainingApplied()}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "IsChainingApplied returns false -- empty, no chaining", actual)
	})
}

func Test_NonChainedLinkedCollectionNodes_ApplyChaining_multi_FromS20(t *testing.T) {
	safeTest(t, "Test_NonChainedLinkedCollectionNodes_ApplyChaining_multi_FromS20", func() {
		// Arrange
		nodes := corestr.NewNonChainedLinkedCollectionNodes(5)
		col1 := corestr.New.Collection.Strings([]string{"a"})
		col2 := corestr.New.Collection.Strings([]string{"b"})
		col3 := corestr.New.Collection.Strings([]string{"c"})
		lc1 := corestr.New.LinkedCollection.UsingCollections(col1)
		lc2 := corestr.New.LinkedCollection.UsingCollections(col2)
		lc3 := corestr.New.LinkedCollection.UsingCollections(col3)
		nodes.Adds(lc1.Head(), lc2.Head(), lc3.Head())

		// Act
		result := nodes.ApplyChaining()

		// Assert
		actual := args.Map{"result": result != nodes}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "ApplyChaining returns self", actual)
		actual = args.Map{"result": nodes.IsChainingApplied()}
		expected = args.Map{"result": true}
		expected.ShouldBeEqual(t, 0, "IsChainingApplied returns true -- applied", actual)
		actual = args.Map{"result": nodes.Last().HasNext()}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Last node has nil next -- end of chain", actual)
	})
}

func Test_NonChainedLinkedCollectionNodes_Items_FromS20(t *testing.T) {
	safeTest(t, "Test_NonChainedLinkedCollectionNodes_Items_FromS20", func() {
		// Arrange
		nodes := corestr.NewNonChainedLinkedCollectionNodes(5)

		// Act
		items := nodes.Items()

		// Assert
		actual := args.Map{"result": items == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Items returns non-nil -- empty but initialized", actual)
	})
}

func Test_NonChainedLinkedCollectionNodes_ToChainedNodes_empty_FromS20(t *testing.T) {
	safeTest(t, "Test_NonChainedLinkedCollectionNodes_ToChainedNodes_empty_FromS20", func() {
		// Arrange
		nodes := corestr.NewNonChainedLinkedCollectionNodes(5)

		// Act
		chained := nodes.ToChainedNodes()

		// Assert
		actual := args.Map{"result": chained == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "ToChainedNodes returns non-nil -- empty input", actual)
	})
}

func Test_NonChainedLinkedCollectionNodes_ToChainedNodes_multi_FromS20(t *testing.T) {
	safeTest(t, "Test_NonChainedLinkedCollectionNodes_ToChainedNodes_multi_FromS20", func() {
		// Arrange
		nodes := corestr.NewNonChainedLinkedCollectionNodes(5)
		col1 := corestr.New.Collection.Strings([]string{"a"})
		col2 := corestr.New.Collection.Strings([]string{"b"})
		lc1 := corestr.New.LinkedCollection.UsingCollections(col1)
		lc2 := corestr.New.LinkedCollection.UsingCollections(col2)
		nodes.Adds(lc1.Head(), lc2.Head())

		// Act
		chained := nodes.ToChainedNodes()

		// Assert
		actual := args.Map{"result": chained == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "ToChainedNodes returns non-nil -- has items", actual)
	})
}

