// MIT License
// 
// Copyright (c) 2020–2026
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package corestrtests

// Auto-generated by Batch 2.2 split from S20_001_S20_NonChainedNodes_HashmapDiff_test.go.
// See spec/01-app/29-corestrtests-phase2-merge-plan.md.

import (
	"testing"

	"github.com/alimtvnetwork/core-v8/coredata/corestr"
	"github.com/alimtvnetwork/core-v8/coretests/args"
)

func Test_NonChainedLinkedListNodes_NewNonChainedLinkedListNodes_creates_with_capacity_FromS20(t *testing.T) {
	safeTest(t, "Test_NonChainedLinkedListNodes_NewNonChainedLinkedListNodes_creates_with_capacity_FromS20", func() {
		// Arrange
		capacity := 5

		// Act
		nodes := corestr.NewNonChainedLinkedListNodes(capacity)

		// Assert
		actual := args.Map{"result": nodes == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "NewNonChainedLinkedListNodes returns nil -- capacity 5", actual)
		actual = args.Map{"result": nodes.Length() != 0}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Length returns 0 -- empty after creation", actual)
		actual = args.Map{"result": nodes.IsEmpty()}
		expected = args.Map{"result": true}
		expected.ShouldBeEqual(t, 0, "IsEmpty returns true -- no items added", actual)
		actual = args.Map{"result": nodes.HasItems()}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "HasItems returns false -- no items added", actual)
	})
}

func Test_NonChainedLinkedListNodes_Adds_single_FromS20(t *testing.T) {
	safeTest(t, "Test_NonChainedLinkedListNodes_Adds_single_FromS20", func() {
		// Arrange
		nodes := corestr.NewNonChainedLinkedListNodes(5)
		ll := corestr.New.LinkedList.SpreadStrings("a", "b")
		head := ll.Head()

		// Act
		nodes.Adds(head)

		// Assert
		actual := args.Map{"result": nodes.Length() != 1}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Length returns 1 -- one node added", actual)
		actual = args.Map{"result": nodes.IsEmpty()}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "IsEmpty returns false -- has items", actual)
		actual = args.Map{"result": nodes.HasItems()}
		expected = args.Map{"result": true}
		expected.ShouldBeEqual(t, 0, "HasItems returns true -- has items", actual)
	})
}

func Test_NonChainedLinkedListNodes_Adds_nil_FromS20(t *testing.T) {
	safeTest(t, "Test_NonChainedLinkedListNodes_Adds_nil_FromS20", func() {
		// Arrange
		nodes := corestr.NewNonChainedLinkedListNodes(5)

		// Act
		result := nodes.Adds(nil...)

		// Assert
		actual := args.Map{"result": result != nodes}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Adds returns self -- nil input", actual)
		actual = args.Map{"result": nodes.Length() != 0}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Length returns 0 -- nil not added", actual)
	})
}

func Test_NonChainedLinkedListNodes_First_Last_FromS20(t *testing.T) {
	safeTest(t, "Test_NonChainedLinkedListNodes_First_Last_FromS20", func() {
		// Arrange
		nodes := corestr.NewNonChainedLinkedListNodes(5)
		ll := corestr.New.LinkedList.SpreadStrings("alpha", "beta", "gamma")
		head := ll.Head()
		node2 := head.Next()
		node3 := node2.Next()

		// Act
		nodes.Adds(head, node2, node3)

		// Assert
		actual := args.Map{"result": nodes.First().Element != "alpha"}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "First returns alpha -- first added", actual)
		actual = args.Map{"result": nodes.Last().Element != "gamma"}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Last returns gamma -- last added", actual)
	})
}

func Test_NonChainedLinkedListNodes_FirstOrDefault_empty_FromS20(t *testing.T) {
	safeTest(t, "Test_NonChainedLinkedListNodes_FirstOrDefault_empty_FromS20", func() {
		// Arrange
		nodes := corestr.NewNonChainedLinkedListNodes(5)

		// Act
		result := nodes.FirstOrDefault()

		// Assert
		actual := args.Map{"result": result != nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "FirstOrDefault returns nil -- empty nodes", actual)
	})
}

func Test_NonChainedLinkedListNodes_LastOrDefault_empty_FromS20(t *testing.T) {
	safeTest(t, "Test_NonChainedLinkedListNodes_LastOrDefault_empty_FromS20", func() {
		// Arrange
		nodes := corestr.NewNonChainedLinkedListNodes(5)

		// Act
		result := nodes.LastOrDefault()

		// Assert
		actual := args.Map{"result": result != nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "LastOrDefault returns nil -- empty nodes", actual)
	})
}

func Test_NonChainedLinkedListNodes_FirstOrDefault_has_items_FromS20(t *testing.T) {
	safeTest(t, "Test_NonChainedLinkedListNodes_FirstOrDefault_has_items_FromS20", func() {
		// Arrange
		nodes := corestr.NewNonChainedLinkedListNodes(5)
		ll := corestr.New.LinkedList.SpreadStrings("x")
		nodes.Adds(ll.Head())

		// Act
		result := nodes.FirstOrDefault()

		// Assert
		actual := args.Map{"result": result == nil || result.Element != "x"}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "FirstOrDefault returns x -- single item", actual)
	})
}

func Test_NonChainedLinkedListNodes_LastOrDefault_has_items_FromS20(t *testing.T) {
	safeTest(t, "Test_NonChainedLinkedListNodes_LastOrDefault_has_items_FromS20", func() {
		// Arrange
		nodes := corestr.NewNonChainedLinkedListNodes(5)
		ll := corestr.New.LinkedList.SpreadStrings("x", "y")
		nodes.Adds(ll.Head(), ll.Head().Next())

		// Act
		result := nodes.LastOrDefault()

		// Assert
		actual := args.Map{"result": result == nil || result.Element != "y"}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "LastOrDefault returns y -- two items", actual)
	})
}

func Test_NonChainedLinkedListNodes_IsChainingApplied_false_FromS20(t *testing.T) {
	safeTest(t, "Test_NonChainedLinkedListNodes_IsChainingApplied_false_FromS20", func() {
		// Arrange
		nodes := corestr.NewNonChainedLinkedListNodes(5)

		// Act
		result := nodes.IsChainingApplied()

		// Assert
		actual := args.Map{"result": result}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "IsChainingApplied returns false -- not applied yet", actual)
	})
}

func Test_NonChainedLinkedListNodes_ApplyChaining_empty_FromS20(t *testing.T) {
	safeTest(t, "Test_NonChainedLinkedListNodes_ApplyChaining_empty_FromS20", func() {
		// Arrange
		nodes := corestr.NewNonChainedLinkedListNodes(5)

		// Act
		result := nodes.ApplyChaining()

		// Assert
		actual := args.Map{"result": result != nodes}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "ApplyChaining returns self -- empty nodes", actual)
		actual = args.Map{"result": nodes.IsChainingApplied()}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "IsChainingApplied returns false -- empty, no chaining applied", actual)
	})
}

func Test_NonChainedLinkedListNodes_ApplyChaining_multi_FromS20(t *testing.T) {
	safeTest(t, "Test_NonChainedLinkedListNodes_ApplyChaining_multi_FromS20", func() {
		// Arrange
		nodes := corestr.NewNonChainedLinkedListNodes(5)
		// Create individual nodes (not chained)
		ll1 := corestr.New.LinkedList.SpreadStrings("a")
		ll2 := corestr.New.LinkedList.SpreadStrings("b")
		ll3 := corestr.New.LinkedList.SpreadStrings("c")
		nodes.Adds(ll1.Head(), ll2.Head(), ll3.Head())

		// Act
		result := nodes.ApplyChaining()

		// Assert
		actual := args.Map{"result": result != nodes}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "ApplyChaining returns self", actual)
		actual = args.Map{"result": nodes.IsChainingApplied()}
		expected = args.Map{"result": true}
		expected.ShouldBeEqual(t, 0, "IsChainingApplied returns true -- chaining applied", actual)
		first := nodes.First()
		actual = args.Map{"result": first.Next() == nil || first.Next().Element != "b"}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "ApplyChaining chains a->b -- correct next", actual)
		actual = args.Map{"result": nodes.Last().HasNext()}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Last node has nil next -- end of chain", actual)
	})
}

func Test_NonChainedLinkedListNodes_Items_FromS20(t *testing.T) {
	safeTest(t, "Test_NonChainedLinkedListNodes_Items_FromS20", func() {
		// Arrange
		nodes := corestr.NewNonChainedLinkedListNodes(5)
		ll := corestr.New.LinkedList.SpreadStrings("x")
		nodes.Adds(ll.Head())

		// Act
		items := nodes.Items()

		// Assert
		actual := args.Map{"result": len(items) != 1}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "Items returns 1 item -- one added", actual)
	})
}

func Test_NonChainedLinkedListNodes_ToChainedNodes_FromS20(t *testing.T) {
	safeTest(t, "Test_NonChainedLinkedListNodes_ToChainedNodes_FromS20", func() {
		// Arrange
		nodes := corestr.NewNonChainedLinkedListNodes(5)
		ll := corestr.New.LinkedList.SpreadStrings("a", "b")
		nodes.Adds(ll.Head(), ll.Head().Next())

		// Act
		chained := nodes.ToChainedNodes()

		// Assert
		actual := args.Map{"result": chained == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "ToChainedNodes returns non-nil -- has items", actual)
	})
}

func Test_NonChainedLinkedListNodes_ToChainedNodes_empty_FromS20(t *testing.T) {
	safeTest(t, "Test_NonChainedLinkedListNodes_ToChainedNodes_empty_FromS20", func() {
		// Arrange
		nodes := corestr.NewNonChainedLinkedListNodes(5)

		// Act
		chained := nodes.ToChainedNodes()

		// Assert
		actual := args.Map{"result": chained == nil}
		expected := args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "ToChainedNodes returns non-nil slice -- empty input", actual)
		actual = args.Map{"result": len(chained) != 0}
		expected = args.Map{"result": false}
		expected.ShouldBeEqual(t, 0, "ToChainedNodes returns empty slice -- empty input", actual)
	})
}

